version: '3'
services:
  # バックエンド
  demo-app:
    build: .
    image: lambda-try:v1
    container_name: 'lambda-try'
    tty: true
    volumes:
      - ./src:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
    environment:
      - DEFAULT_REGION=ap-northeast-1